function tableout = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   ProjeDATA = importfile('Proje_DATA.xlsx','Sheet1',2,769);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2015/12/16 09:33:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 769;
end

%% Import the data
data = [xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(1),endRow(1))),...
    xlsread(workbookFile, sheetName, sprintf('G%d:G%d',startRow(1),endRow(1))),...
    xlsread(workbookFile, sheetName, sprintf('I%d:I%d',startRow(1),endRow(1)))];
for block=2:length(startRow)
    tmpDataBlock = [xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(block),endRow(block))),...
        xlsread(workbookFile, sheetName, sprintf('G%d:G%d',startRow(block),endRow(block))),...
        xlsread(workbookFile, sheetName, sprintf('I%d:I%d',startRow(block),endRow(block)))];
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.ins = data(:,1);
tableout.pedi = data(:,2);
tableout.y = data(:,3);

